import os
from dotenv import load_dotenv

load_dotenv()

CHROMA_DATABASE_PATH = os.getenv("CHROMA_LLM_CHATBOT_DATABASE_PATH")
COLLECTION_NAME = os.getenv("CHROMA_LLM_CHATBOT_COLLECTION_NAME")
CHUNK_SIZE = int(os.getenv("CHROMA_LLM_CHATBOT_CHUNK_SIZE"))
CHUNK_OVERLAP = int(os.getenv("CHROMA_LLM_CHATBOT_CHUNK_OVERLAP"))
MODEL_PATH = os.getenv("CHROMA_LLM_CHATBOT_MODEL_PATH")
NUMBER_OF_MOST_SIMILAR_DOCUMENTS_TO_RETRIEVE = int(os.getenv("CHROMA_LLM_CHATBOT_NUMBER_OF_MOST_SIMILAR_DOCUMENTS_TO_RETRIEVE"))
CONTEXT_SIZE = int(os.getenv("CHROMA_LLM_CHATBOT_LLM_CONTEXT_SIZE"))
NUMBER_OF_THREADS = int(os.getenv("CHROMA_LLM_CHATBOT_NUMBER_OF_THREADS"))
MAX_TOKENS = int(os.getenv("CHROMA_LLM_CHATBOT_LLM_MAX_TOKENS"))
VERBOSE_OUTPUT_ENABLED = os.getenv("CHROMA_LLM_CHATBOT_LLM_VERBOSE_OUTPUT_ENABLED") == 'enabled'
OFFLINE_MODE_ENABLED = os.getenv("CHROMA_LLM_CHATBOT_OFFLINE_MODE_ENABLED") == 'enabled'
